site_name: MapManager
site_url: https://mapmanager.net/
site_description: Software projects by Robert H. Cudmore

copyright: Copyright Robert H. Cudmore 2026 · robert.cudmore@gmail.com

extra:
  generator: false

theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: indigo

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - macros:
      include_yaml:
        - projects: project-cards.yml
      on_error_fail: true
      on_undefined: strict

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md

use_directory_urls: true
